languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Amirul Lokman"
logo = "img/home_logo.png"
description = "My personal website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
    name = "Amirul Lokman"
    # image = "img/blowfish_logo.png"
    headline = "Learning how to build cool stuff :smiling_face_with_sunglasses:"
    bio = "Hello, there :saluting_face:"
    links = [
        { linkedin = "https://linkedin.com/in/amrllkmn" },
        { github = "https://github.com/amrllkmn" }
    ]
